[package]
name = "music_player"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.7"  # Latest stable version as of Feb 2025
rodio = "0.19" # For audio playback
rfd = "0.14"   # For file dialogs
id3 = "1.16.2" # Metadata tags

[build-dependencies]
slint-build = "1.9.2"